changelog:
  categories:
    - title: Features
      labels:
        - feat
    - title: Fixes
      labels:
        - fix
    - title: Tests
      labels:
        - test
    - title: CI/CD
      labels:
        - ci
        - build
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
    - title: Other Changes
      labels:
        - "*"
